# Site settings
title: 1GB&J Creating Apps for YOU
description: GB&J Creating Apps for YOU
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://gbjmobile.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: GB&J LLC
user_description: Our story begins in university where a group of friends wanted to create a motivational app that we would use for ourselves to keep motivated while studying Electrical and Computer Engineering. While developing this app, we found it to be so helpful that we decided we wanted to release it on the market to help everyone get a little motivation throughout the day. Using our names (Gabriel, Blake, & James) we formed GB&J (like PB&J the sandwich) LLC, as like a perfect PB&J our skills are complementary and form the perfect team. This was the inspiration behind Sammy the Sandwich, our company mascot :) Follow us to keep up to date with our latest apps! 
user_title: App Development Company
email: contact@GBJmobile.com
facebook_username: lorem_ipsum
instagram_username:  lorem_ipsum
twitter_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
